### ISSUE TITLE
No se reciben datos

### ISSUE THREAD

**Issue by galambert75** [Danieldiazi/homeassistant-meteogalicia#2]
![MeteoGalicia](https://user-images.githubusercontent.com/97364232/209973395-04bfb27c-6b36-48cb-9820-328468d890f3.jpg)

**Comment by Danieldiazi** [comment]
Boas!
Parece que algo está fallando en los servicios web de MeteoGalicia, pues devuelve a veces un error 500 y otras un 404:

Por ejemplo: https://servizos.meteogalicia.gal/mgrss/predicion/jsonPredConcellos.action?idConc=36038 


![imagen](https://user-images.githubusercontent.com/3638478/209978483-d2863fb9-1bac-4a60-b6b7-e0b4cdb20998.png)

A ver qué averiguo!

**Comment by galambert75** [comment]
Gracias!

Ahora me llegan algunos valores y otros no. Seguro es problema de MeteoGalicia.

Excelente integración, por cierto.

**Comment by Danieldiazi** [comment]
Si, les he escrito para notificarles el problema, pero ya estaban al tanto. Parece que el problema aún persiste, ahora ya no me da 404, simplemente tarda mucho en cargar.

Gracias por avisar y por tus palabras, aún estoy aprendiendo, pero si la integración es útil, genial!

**Comment by Danieldiazi** [comment]
Parece que ya funciona, lo damos por solucionado. Gracias por avisar.
