### ISSUE TITLE
Tratar el caso de medidas de atributos que lleguen con valor a -9999 en la información de datos de estación

### ISSUE THREAD

**Issue by Danieldiazi** [Danieldiazi/homeassistant-meteogalicia#6]
> Holas:
> 
> Genial, espero que siga yendo bien, en mi caso así es.

Hola Daniel,

Sigue yendo bien. Creo que ya puedes dar por cerrado el issue.

Respecto al tema de combinar el valor y la unidad, tienes razón. Al final lo que hice fue crear sensores "template" para monitorizar los parámetros que me interesan como "measurement". Incluí el filtrado de -9999 (no disponible) que se muestra de madrugada porque me distorsionaba las gráficas. 

```
  - sensor:
      - name: "MeteoGalicia - Areas - Balance Hidrico Diario"
        unique_id: meteogalicia_areas_bh_daily
        icon: mdi:waves-arrow-up
        unit_of_measurement: "L/m2"
        state: >
          {% if (((state_attr("sensor.meteogalicia_19055_station_daily_data", "BH_SUM_1.5m_value")) | float)==-9999) -%}
            {{ "unknown" }}
          {%- else -%}
            {{ state_attr("sensor.meteogalicia_19055_station_daily_data", "BH_SUM_1.5m_value") | float }}
          {%- endif %}
        state_class: measurement

```

Mil gracias!

_Originally posted by @galambert75 in https://github.com/Danieldiazi/homeassistant-meteogalicia/issues/5#issuecomment-1691391584_

**Comment by Danieldiazi** [comment]
Más info relativa a este problema: https://github.com/Danieldiazi/homeassistant-meteogalicia/issues/5#issuecomment-1691479292 y en https://github.com/Danieldiazi/homeassistant-meteogalicia/issues/5#issuecomment-1691485925

**Comment by Danieldiazi** [comment]
Hola:
La nueva versión solucionará este caso, devolviendo valor nulo para aquellos atributos con valor -9999.
En el código que tienes de ejemplo ya no te hará falta controlar si es ese valor, pero si, si es nulo.

Un ejemplo:

```
{% if state_attr('sensor.meteogalicia_10124_station_last_10_min_data_dv_avg_10m', 'DV_AVG_10m_value') is not none -%}
 Valor {{ state_attr("sensor.meteogalicia_10124_station_last_10_min_data_dv_avg_10m", "DV_AVG_10m_value") | float }}
{%- endif %}
```

**Comment by Danieldiazi** [comment]
Versión en fase de pruebas: https://github.com/Danieldiazi/homeassistant-meteogalicia/releases/tag/2023.8.5-Beta1

**Comment by galambert75** [comment]
Gracias Daniel! Lo he instalado y estaré pendiente.

**Comment by galambert75** [comment]
Gracias Daniel!

Ya instalé la última versión. También me va todo estable!
