### ISSUE TITLE
Sensores de estaciones meteorológicas "unavailable" según estado al reiniciar

### ISSUE THREAD

**Issue by galambert75** [Danieldiazi/homeassistant-meteogalicia#7]
Hola Daniel,

Creo que he detectado un bug en los sensores correspondientes a estaciones meteorológicas. Se produce al reiniciar Home Assistant si el Webservice devuelve un valor "unavailable" o si no hay conectividad al webservice.

Me ha sucedido dos veces:

1. Al actualizar la versión de Home Assistant a 2023.9.0 - Lo hice poco después de medianoche. Como el webservice devuelve el valor "unavailable" entre las 00:00 y las 02:00 (el motivo ya lo explicaste tú en otro post), el sensor diario queda en "unavailable". El sensor diezminutal sí que está disponible (el webservice nunca devuelve "unavailable"). Para volver a recuperar el sensor diario tengo que reiniciar Home Assistant (no vale con reiniciar solo el YAML, tengo que hacer un reinicio completo).
2. Con la tormenta de hoy hubo un corte de luz - Cuando volvió la luz, Home Assistant levantó antes que mi router. Como no había conectividad a internet, Home Assistant no llegaba al web service. Tanto la entidad de estación meteorológica diaria como la diezminutal quedaron en "unavailable". Sin embargo, los datos del municipio sí que se recuperaron cuando hubo conexión a internet. Para recuperar los de la estación meteorológica tuve que reiniciar.

Todo apunta a que el sensor queda "pillado" si el valor inicial de la estación meteorológica es "unavailable". 

Cualquier duda, avísame!

**Comment by Danieldiazi** [comment]
Una pregunta @galambert75 : En entidades te aparece este mensaje en aquella que no se recupera si no reinicias: "La integración meteogalicia ya no proporciona esta entidad. Si la entidad ya no está en uso, elimínala en la configuración."

**Comment by galambert75** [comment]
Pues no me fijé. Creo que sí, porque en el histórico de la entidad aparece como si no existiera. 

En el pantallazo se ve lo que pasó con el reinicio por actualización (8-sep a las 00:00) y por corte de luz (9-sep a las 12:00). 

![image](https://github.com/Danieldiazi/homeassistant-meteogalicia/assets/97364232/a8922a54-9eac-44bc-ada9-9b7d0c920991)

**Comment by Danieldiazi** [comment]
Hay una nueva versión.  Resuelve el punto 2 que comentabas. El 1º no lo he visto, pero tengo sospechas de que sea por lo mismo.  Puede ser que uses el parámetro "id_estacion_medida_diarios" en el caso de que te falla del punto 1?

**Comment by galambert75** [comment]
Gracias Daniel! Ya la bajé ayer. Seguro que tienes razón. Estaré atento y, si se vuelve a producir el fallo, aviso.

Esta es la configuración:

```
sensor:
  - platform: meteogalicia
    id_concello: !secret meteogalicia_concello
    scan_interval: 300

  - platform: meteogalicia
    id_estacion: !secret meteogalicia_estacion
    scan_interval: 300

```

**Comment by Danieldiazi** [comment]
Hola @galambert75 , la versión de ayer era por otra mejora, la que puede corregir tu bug, es esta que he publicado hoy :)
Dejo la "issue" abierta hasta confirmar también el punto 1.
Saludos!

**Comment by galambert75** [comment]
> Hola @galambert75 , la versión de ayer era por otra mejora, el caso de que un usuario pusiese un id de estación que realmente no existe, la que puede corregir tu bug, es esta que he publicado hoy :) Dejo la "issue" abierta hasta confirmar también el punto 1. Saludos!

Versión nueva instalada.

Un saludo!

**Comment by Danieldiazi** [comment]
He chequeado el punto 1:

**INTERVALO SIN DATOS**
En el momento que no facilita datos, da el siguiente mensaje de error en los logs
"En estos momentos da "Currently unable to download asked data from MeteoGalicia: Or station id: XXXX doesn't exists or there are a possible API connection problem", que es lo esperado puesto que no hay datos del servicio web en este intervalo de tiempo. 
"

Pero el sensor si que existe.
**INTERVALO CON DATOS**
Cuando volvemos a tener datos y en función del "scan_interval" que le hayamos puesto  vuelve a conectarse, funcionando ya como debería.
![imagen](https://github.com/Danieldiazi/homeassistant-meteogalicia/assets/3638478/496a62c1-2b32-496a-a75b-fda166bc3dd8)

Así que todo apunta a que funciona como debería.

**Comment by Danieldiazi** [comment]
He comprobado que hoy también sigue funcionando correctamente  con la versión desplegada ( https://github.com/Danieldiazi/homeassistant-meteogalicia/releases/tag/2023.9.2 ) . Procedo a cerrar el bug, pero si hay cualquier cosa, lo vuelvo a reabrir.
